version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.Web.Lib/"
    target-branch: "development"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.Web.Lib.Components/"
    target-branch: "development"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"