version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.Web.Lib/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.Web.Lib.Components/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"