version: 2
updates:
  # NuGet config for SmallsOnline.Web.Lib
  - package-ecosystem: "nuget"
    directory: "/src/Lib/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "library"
      - "dependency update"
    assignees:
      - "Smalls1652"
  
  # NuGet config for SmallsOnline.Web.Lib.Components
  - package-ecosystem: "nuget"
    directory: "/src/Lib.Components/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "library"
      - "dependency update"
    ignore:
      - dependency-name: "Markdig"
      - dependency-name: "YamlDotNet"
    assignees:
      - "Smalls1652"

  # NuGet config for SmallsOnline.Web.PublicSite.Server
  - package-ecosystem: "nuget"
    directory: "/src/PublicSite/Server"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "website"
      - "dependency update"
    ignore:
      - dependency-name: "Markdig"
      - dependency-name: "YamlDotNet"
    assignees:
      - "Smalls1652"

  # NPM config for SmallsOnline.Web.PublicSite.Server
  - package-ecosystem: "npm"
    directory: "/src/PublicSite/Server"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "website"
      - "dependency update"
    assignees:
      - "Smalls1652"

  # NuGet config for SmallsOnline.Web.Lib.Services
  - package-ecosystem: "nuget"
    directory: "/src/Lib.Services"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "middleware"
      - "dependency update"
    assignees:
      - "Smalls1652"

  # NuGet config for SmallsOnline.Web.Api
  - package-ecosystem: "nuget"
    directory: "/src/Api"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "api"
      - "dependency update"
    ignore:
      - dependency-name: "Markdig"
      - dependency-name: "YamlDotNet"
    assignees:
      - "Smalls1652"

  # Config for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    ignore:
      - dependency-name: "Markdig"
      - dependency-name: "YamlDotNet"
    assignees:
      - "Smalls1652"