FROM mcr.microsoft.com/dotnet/sdk:8.0-preview as build-env
WORKDIR /app

COPY ./src/Lib/ ./src/Lib/
COPY ./src/Api/ ./src/Api/

RUN dotnet restore ./src/Api/
RUN dotnet publish ./src/Api/ --configuration "Release" --runtime "linux-x64" -p:"PublishReadyToRun=true" --output out

FROM mcr.microsoft.com/dotnet/aspnet:8.0-preview
WORKDIR /app

COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "SmallsOnline.Web.Api.dll"]
EXPOSE 80