name: Update or change
description: Proposals for updates or changes
labels:
  - "update"
title: "[Update]: "
body:
  - id: ChangeType
    type: dropdown
    attributes:
      label: What kind of update/change is this?
      description: The type of update/change this will have.
      multiple: false
      options:
        - "Addition"
        - "Change/Update"
        - "Removal"
    validations:
      required: true
  - id: Project
    type: dropdown
    attributes:
      label: What project(s) does this affect?
      description: The project(s) that are affected by this update/change.
      multiple: true
      options:
        - "Core class library"
        - "Core component library"
        - "Public website"
        - "Admin website"
        - "Other"
    validations:
      required: true
  - id: Description
    type: textarea
    attributes:
      label: What's the description of the change?
      description: A description of the change.
      placeholder: Insert a detailed description of the change...
    validations:
      required: true
  - id: ProposedChangesDescription
    type: textarea
    attributes:
      label: What are the proposed changes that need to be made?
      description: A technical description of the proposed changes to be made. (Not required)
      placeholder: Insert the technical description of the changes...
    validations:
      required: false