# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Admin Website / Build
on:
  push:
    tags-ignore: [ 'v*.*.*', 'v*.*.*-*' ]
    paths-ignore:
      - "src/Tools/**"
      - "src/PublicSite/**"
  pull_request:
    paths-ignore:
      - "src/Tools/**"
      - "src/PublicSite/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build-lib:
    name: Build web app
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Configure GitHub NuGet package source
        shell: pwsh
        run: |
          dotnet nuget add source --name "github" --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Build web app
        shell: pwsh
        run: dotnet restore ; dotnet build
        working-directory: "src/AdminSite/Server/"