# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: BlogPublisher CLI Tool / Build
on:
  push:
    paths-ignore:
      - "src/PublicSite/**"
      - "src/Api/**"
  pull_request:
    paths-ignore:
      - "src/PublicSite/**"
      - "src/Api/**"
  workflow_dispatch:

jobs:
  build-blogpublisher:
    name: Build SmallsOnline.Web.Tools.BlogPublisher
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          dotnet-quality: "daily"

      - name: Build BlogPublisher
        shell: pwsh
        run: dotnet restore ./src/Tools/BlogPublisher ; dotnet build ./src/Tools/BlogPublisher