# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: BlogPublisher CLI Tool / Build
on:
  push:
    tags-ignore: [ 'v*.*.*', 'v*.*.*-*' ]
    paths-ignore:
      - "src/PublicSite/**"
      - "src/AdminSite/**"
  pull_request:
    paths-ignore:
      - "src/PublicSite/**"
      - "src/AdminSite/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build-blogpublisher:
    name: Build SmallsOnline.Web.Tools.BlogPublisher
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Configure GitHub NuGet package source
        shell: pwsh
        run: |
          dotnet nuget add source --name "github" --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Build BlogPublisher
        shell: pwsh
        run: dotnet restore ./src/Tools/BlogPublisher ; dotnet build ./src/Tools/BlogPublisher