name: BlogPublisher CLI Tool / Publish

on:
  # Automatically trigger it when detected changes in repo
  # for tagged releases matching 'v*.*.*'
  push:
    tags: [ 'v*.*.*', 'v*.*.*-*' ]
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'dotnet: Setup SDK'
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Configure GitHub NuGet package source
        shell: pwsh
        run: |
          dotnet nuget add source --name "github" --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Install .NET tools
        run: dotnet tool restore

      - name: Update project files with gitversion
        run: dotnet tool run dotnet-gitversion /updateprojectfiles

      - name: 'dotnet: Restore'
        shell: pwsh
        run: |
          dotnet restore ./src/Tools/BlogPublisher/

      - name: 'dotnet: Create package'
        shell: pwsh
        run: |
          dotnet pack ./src/Tools/BlogPublisher/ --configuration Release --no-restore --output ./src/Tools/BlogPublisher/

      - name: 'dotnet: Publish package to registry'
        shell: pwsh
        run: |
          dotnet nuget push "./src/Tools/BlogPublisher/*.nupkg" --source "github"