# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Class library / Build
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-lib:
    name: Build SmallsOnline.Web.Lib
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          dotnet-quality: "daily"

      - name: Build library
        shell: pwsh
        run: dotnet restore ./src/Lib/ ; dotnet build ./src/Lib/

      - name: Build component library
        shell: pwsh
        run: dotnet restore ./src/Lib.Components/ ; dotnet build ./src/Lib.Components/