# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Class library / Build
on:
  push:
    tags-ignore: [ 'v*.*.*', 'v*.*.*-*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build-lib:
    name: Build SmallsOnline.Web.Lib
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Configure GitHub NuGet package source
        shell: pwsh
        run: |
          dotnet nuget add source --name "github" --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Build library
        shell: pwsh
        run: dotnet restore ./src/Lib/ ; dotnet build ./src/Lib/

      - name: Build component library
        shell: pwsh
        run: dotnet restore ./src/Lib.Components/ ; dotnet build ./src/Lib.Components/