# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Class library / Build
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-lib:
    name: Build SmallsOnline.Web.Lib
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          global-json-file: global.json

      - name: Build library
        shell: pwsh
        run: dotnet restore ./src/SmallsOnline.Web.Lib/ ; dotnet build ./src/SmallsOnline.Web.Lib/

      - name: Build component library
        shell: pwsh
        run: dotnet restore ./src/SmallsOnline.Web.Lib.Components/ ; dotnet build ./src/SmallsOnline.Web.Lib.Components/