name: Publish release package
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Configure GitHub package registry source
        run: dotnet nuget add source --username Smalls1652 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Smalls1652/index.json"

      - name: Run dotnet restore
        run: dotnet restore ./src/SmallsOnline.Web.Lib/
      
      - name: Create package
        run: dotnet pack ./src/SmallsOnline.Web.Lib/ --configuration Release --no-restore --output .

      - name: Publish package
        run: dotnet nuget push "*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }}