name: Trigger auto deployment for smallsonline-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ production ]
    paths:
    - '**'
    - '.github/workflows/smallsonline-api-AutoDeployTrigger-577749cb-48c7-42ee-914c-80925d0d9cd2.yml'

  # Allow manually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: smallsonlinecontainerreg.azurecr.io
          username: ${{ secrets.SMALLSONLINEAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.SMALLSONLINEAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: smallsonlinecontainerreg.azurecr.io/api/public:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SMALLSONLINEAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n smallsonline-api -g smalls-online-api --server smallsonlinecontainerreg.azurecr.io --username  ${{ secrets.SMALLSONLINEAPI_REGISTRY_USERNAME }} --password ${{ secrets.SMALLSONLINEAPI_REGISTRY_PASSWORD }}
            az containerapp update -n smallsonline-api -g smalls-online-api --image smallsonlinecontainerreg.azurecr.io/api/public:${{ github.sha }}
