name: Trigger auto deployment for smallsonline-api

# When this action will be executed
on:
  # Automatically trigger when 
  push:
    tags: [ 'v*.*.*' ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update NuGet config file
        shell: pwsh
        run: (Get-Content -Path ".\nuget.raw" -Raw).Replace("{{TOKEN}}", "${{ secrets.PACKAGES_TOKEN }}") | Out-File -FilePath ".\nuget.raw" -Force

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: smallsonlinecontainerreg.azurecr.io
          username: ${{ secrets.SMALLSONLINEAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.SMALLSONLINEAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: smallsonlinecontainerreg.azurecr.io/smallsonline-api:${{ github.ref_name }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      revisionPrefixName: ""
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SMALLSONLINEAPI_AZURE_CREDENTIALS }}


      - name: Set revision prefix
        shell: pwsh
        run: |
          [System.Environment]::SetEnvironmentVariable("revisionPrefixName", ("${{ github.ref_name }}" -replace "\.","-"))


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n smallsonline-api -g smalls-online-api --server smallsonlinecontainerreg.azurecr.io --username  ${{ secrets.SMALLSONLINEAPI_REGISTRY_USERNAME }} --password ${{ secrets.SMALLSONLINEAPI_REGISTRY_PASSWORD }}
            az containerapp update --resource-group smalls-online-api --name smallsonline-api --image smallsonlinecontainerreg.azurecr.io/smallsonline-api:${{ github.ref_name }} --revision-suffix "${{ env.revisionPrefixName }}"
