# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CosmosDB Service / Build
on:
  push:
    paths-ignore:
      - 'src/SmallsOnline.Web.PublicSite/**'
  pull_request:
    paths-ignore:
      - 'src/SmallsOnline.Web.PublicSite/**'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Build CosmosDB service
        shell: pwsh
        run: dotnet restore ./src/SmallsOnline.Web.Services.CosmosDB/ ; dotnet build ./src/SmallsOnline.Web.Services.CosmosDB/
        