# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Website / Build
on:
  push:
    paths-ignore:
      - 'src/Api/**'
  pull_request:
    paths-ignore:
      - 'src/Api/**'
  workflow_dispatch:

jobs:
  build-lib:
    name: Build web app
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          dotnet-quality: "daily"

      - name: Build web app
        shell: pwsh
        run: dotnet restore ; dotnet build
        working-directory: "src/PublicSite/Server/"