name: Website / Publish to Azure AppService

on:
  # Automatically trigger it when detected changes in repo
  # for tagged releases matching 'v*.*.*'
  push:
    tags: [ 'website-v*.*.*', 'website-v*.*.*-*' ]
  # Push nightly builds
  # Should only pull from the latest tag
  schedule:
    - cron: '0 0 * * *'
  # Allow manual trigger 
  workflow_dispatch: 
    inputs:
      on_latest_tag:
        description: 'Run on the latest tag only.'
        required: false
        type: boolean

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: 'Checkout: Fetch all history'
          uses: actions/checkout@v3
          if: ${{ github.event_name == 'schedule' || inputs.on_latest_tag == true }}
          with:
            fetch-depth: 0

        - name: Get latest tag
          if: ${{ github.event_name == 'schedule' || inputs.on_latest_tag == true }}
          id: get_latest_tag
          run: echo "latest_tag=$(git describe --abbrev=0 --tags 'main' --match 'website-*')" >> $GITHUB_ENV

        - name: 'Checkout: Latest tag'
          uses: actions/checkout@v3
          if: ${{ github.event_name == 'schedule' || inputs.on_latest_tag == true }}
          with:
            ref: ${{ env.latest_tag }}
            submodules: true

        - name: 'Checkout: Latest commit'
          uses: actions/checkout@v3
          if: ${{ inputs.on_latest_tag != true && github.event_name != 'schedule' }}
          with:
            submodules: true

        - name: Get current ticks
          id: get_current_ticks
          shell: pwsh
          run: |
            $currentDateTimeTicks = [System.DateTimeOffset]::Now.UtcTicks
            "current_datetime_ticks=$($currentDateTimeTicks)" >> $env:GITHUB_ENV

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to container registry
          uses: docker/login-action@v2
          with:
            registry: smallsonlinecontainerreg.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Trim ref name (Latest tag)
          if: ${{ github.event_name == 'schedule' || inputs.on_latest_tag == true }}
          shell: pwsh
          id: trim-ref-name-tag
          run: |
            "trimmed_ref_name=$(`"${{ env.latest_tag }}`".Replace('website-', ''))" >> $env:GITHUB_ENV

        - name: Trim ref name (Latest commit)
          if: ${{ inputs.on_latest_tag != true && github.event_name != 'schedule' }}
          shell: pwsh
          id: trim-ref-name-commit
          run: |
            "trimmed_ref_name=$(`"${{ github.ref_name }}`".Replace('website-', ''))" >> $env:GITHUB_ENV

        - name: Build and push container image to registry
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: smallsonlinecontainerreg.azurecr.io/smallsonline-web-publicsite:${{ env.trimmed_ref_name }}_${{ env.current_datetime_ticks }}
            file: ./Dockerfile.publicsite
            context: ./

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'smallsonline-web'
            slot-name: 'production'
            publish-profile: ${{ secrets.WEBSITE_AZUREAPPSVC_PUBLISHPROFILE }}
            images: 'smallsonlinecontainerreg.azurecr.io/smallsonline-web-publicsite:${{ env.trimmed_ref_name }}_${{ env.current_datetime_ticks }}'