# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Website / Build
on:
  push:
    paths-ignore:
      - 'src/SmallsOnline.Web.Services.CosmosDB/**'
      - 'src/SmallsOnline.Web.Api/**'
  pull_request:
    paths-ignore:
      - 'src/SmallsOnline.Web.Services.CosmosDB/**'
      - 'src/SmallsOnline.Web.Api/**'
  workflow_dispatch:

jobs:
  build-lib:
    name: Build web app
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools

      - name: Build web app
        shell: pwsh
        run: dotnet restore ; dotnet build
        working-directory: "src/SmallsOnline.Web.PublicSite/Server/"